#!/bin/bash

# Unified Heterogeneous Networking Middleware
# Linux - MIH Starting Script
# Lingyuan He - 05/2015

#clean all the daemon processes
function clean {
	for p in "mih_usr" "odtone-mihf" "link_sap"; do
        	while true; do
                	echo "ps ax | grep $p$ | awk '{print \$1}'"
                	id="$(ps ax | grep $p$ | awk '{print $1}')"
                	if [ -z  $id ]; then
                        	echo "no process named $p"
                        	break
               		else
				echo -e "kill $id\t($p)"
				sudo kill $id
                        	echo "killed"
                	fi
        	done
	done
}

clean

OMNI_ROOT=
ROOT_DIR=$OMNI_ROOT/protocols/mih/odtone-0.6

pushd $ROOT_DIR/dist

#run odtone-mihf, mih_usr and two link_saps
./odtone-mihf 1> output &
sleep 1
cd 802_3
../link_sap 1> output &
cd ../802_11
../link_sap 1> output &
cd ..
sleep 1
./mih_usr --dest=mihf1

popd

clean
