#!/bin/bash

# Unified Heterogeneous Networking Middleware
# Android - MIH Starting Script

#clean all the daemon processes
function clean {
	for p in "mih_usr" "odtone-mihf" "link_sap"; do # "miis_rdf_server"; do
        	while true; do
                	echo "ps ax | grep $p$ | awk '{print \$1}'"
                	id="$(ps ax | grep $p$ | awk '{print $1}')"
                	if [ -z  $id ]; then
                        	echo "no process named $p"
                        	break
               		else
				echo -e "kill $id\t($p)"
				sudo kill $id
                        	echo "killed"
                	fi
        	done
	done
}

clean

# installation folder on android device
INSTALL_DIR=/data/misc/install

cd $INSTALL_DIR/odtone

#run odtone-mihf, mih_usr and three link_saps
./odtone-mihf 1> output &
sleep 1
#cd 802_3
#../link_sap 1> output &
cd 802_11
../link_sap 1> output &
cd ../lte
../link_sap 1> output &
cd ..
sleep 1
./mih_usr --dest=mihf1

# after mih_usr exit
clean
